name: adroit_door

task_name: door

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
        shape: *image_shape
        type: rgb
        horizon: 2
    agent_pos:
      shape: [24]
      type: low_dim
      horizon: 2
  action:
    shape: [28]
    horizon: 16

env_runner:
  _target_: maniflow.env_runner.adroit_runner.AdroitRunner
  eval_episodes: 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: door
  render_size: 84

dataset:
  _target_: maniflow.dataset.adroit_image_dataset.AdroitImageDataset
  zarr_path: data/adroit_door_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  use_img: true
  use_depth: false
