name: dexart_laptop_image

task_name: laptop

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: [3, 84, 84]
      type: rgb
      horizon: 2
    agent_pos:
      shape: [32]
      type: low_dim
      horizon: 2
  action:
    shape: [22]
    horizon: 16

env_runner:
  _target_: maniflow.env_runner.dexart_runner.DexArtRunner
  n_train: 20
  max_steps: 50
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: laptop
  use_test_env: false

dataset:
  _target_: maniflow.dataset.dexart_image_dataset.DexArtImageDataset
  zarr_path: data/dexart_laptop_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90