defaults:
  # both work for referencing the task config
  - ../robotwin_env/dual_bottles_pick_hard@robotwin_env

name: dual_bottles_pick_hard_pointcloud

shape_meta: &shape_meta
  # acceptable types: point_cloud, low_dim
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [14]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: maniflow.env_runner.robot_runner.RobotRunner
  eval_episodes: 10
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: dual_bottles_pick_hard
  task_config: ${robotwin_task.robotwin_env}

dataset:
  _target_: maniflow.dataset.robotwin_dataset.RoboTwinDataset
  zarr_path: data/dual_bottles_pick_hard_50.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null

  use_pc_color: ${policy.use_pc_color}
  pointcloud_color_aug_cfg:
    aug_color: true
    prob: 0.2
    params: [0.3, 0.4, 0.5, 0.08] # brightness, contrast, saturation, hue

